corresponsalia:
    resource: "@CorresponsaliaBundle/Resources/config/routing.yml"
    prefix:   /corresponsalia

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario
    
login:
    pattern:  /
    defaults: { _controller: UsuarioBundle:Default:index }