corresponsalia:
    resource: "@CorresponsaliaBundle/Resources/config/routing.yml"
    prefix:   /corresponsalia

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario
    
login:
    pattern:  /
    defaults: { _controller: UsuarioBundle:Default:index }
    
CorresponsaliaBundle_tecnocategoria:
        resource: "@CorresponsaliaBundle/Resources/config/routing/tecnologia_categoria.yml"
        prefix:   /tecnocategoria
  
CorresponsaliaBundle_tecnomarca:
        resource: "@CorresponsaliaBundle/Resources/config/routing/tecnologia_marca.yml"
        prefix:   /tecnomarca
        
CorresponsaliaBundle_tecnoequipo:
        resource: "@CorresponsaliaBundle/Resources/config/routing/tecnologia_equipo.yml"
        prefix:   /tecnoequipo
        
CorresponsaliaBundle_tecnoasignar:
        resource: "@CorresponsaliaBundle/Resources/config/routing/tecnologia_asignacion.yml"
        prefix:   /tecnoasignar
        
CorresponsaliaBundle_tecnomodelo:
        resource: "@CorresponsaliaBundle/Resources/config/routing/tecnologia_modelo.yml"
        prefix:   /tecnomodelo

CorresponsaliaBundle_tecnobitacora:
        resource: "@CorresponsaliaBundle/Resources/config/routing/tecnologia_bitacora.yml"
        prefix:   /tecnobitacora
