security:
    firewalls:
        frontend:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: /usuario/login
                check_path: /usuario/login_check
                default_target_path: /corresponsalia/inicio
                always_use_default_target_path: true
            logout:
                path: usuario_logout
                target: /usuario/login


            
    providers:
        usuarios:
            entity: { class: Administracion\UsuarioBundle\Entity\User, property: username }
        
    encoders:
       # Administracion\UsuarioBundle\Entity\User: { algorithm: plaintext }

        Administracion\UsuarioBundle\Entity\User: 
            algorithm: md5
            iterations:       0
            encode_as_base64: false

        #Symfony\Component\Security\Core\User\User: plaintext
        
    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/corresponsalia/inicio, roles: ROLE_USER }
    #ROLES DE MODULO DE PERSONAL
        - { path: ^/corresponsalia/personal,     roles: [ROLE_SUPERADMIN, ROLE_PERSONAL]}
        - { path: ^/corresponsalia/cargo,        roles: [ROLE_SUPERADMIN, ROLE_PERSONAL]}
    #ROLES DE MODULO DE CORRESPONSALIA (DATOS, COMENTARIOS Y DOCUMENTOS)
        - { path: ^/corresponsalia/datoslegales, roles: [ROLE_SUPERADMIN,ROLE_CONSULTORIA]}
        - { path: ^/corresponsalia/comentarios,  roles: [ROLE_SUPERADMIN,ROLE_CONSULTORIA]}
        - { path: ^/corresponsalia/documentos,   roles: [ROLE_SUPERADMIN,ROLE_CONSULTORIA]}
