security:
    firewalls:
        frontend:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: /usuario/login
                check_path: /usuario/login_check
                default_target_path: /corresponsalia/inicio
                always_use_default_target_path: true
            logout:
                path: usuario_logout
                target: /usuario/login


            
    providers:
        usuarios:
            entity: { class: Administracion\UsuarioBundle\Entity\User, property: username }
        
    encoders:
       # Administracion\UsuarioBundle\Entity\User: { algorithm: plaintext }

        Administracion\UsuarioBundle\Entity\User: 
            algorithm: md5
            iterations:       0
            encode_as_base64: false

        #Symfony\Component\Security\Core\User\User: plaintext
        
    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/corresponsalia/inicio, roles: ROLE_USER }

        - { path: ^/usuario, roles: ROLE_SUPERADMIN }
        - { path: ^/corresponsalia/reporte/aurendicion, roles: ROLE_SUPERADMIN }

        - { path: ^/corresponsalia/periodorendicion, roles: [ROLE_RENDICION_ADMIN, ROLE_RENDICION_CORRESPONSALIA] }
        - { path: ^/corresponsalia/reporte/rendicion, roles: [ROLE_RENDICION_ADMIN, ROLE_RENDICION_CORRESPONSALIA,ROLE_SUPERADMIN] }
        - { path: ^/corresponsalia/reporte/auef, roles: [ROLE_RENDICION_ADMIN,ROLE_SUPERADMIN] }

        - { path: ^/corresponsalia/descripciongasto, roles: ROLE_RENDICION_ADMIN }
        - { path: ^/corresponsalia/tipomoneda, roles: ROLE_RENDICION_ADMIN }
        - { path: ^/corresponsalia/tipocorresponsalia, roles: ROLE_RENDICION_ADMIN }
        - { path: ^/corresponsalia/corresponsalia, roles: ROLE_RENDICION_ADMIN }
        - { path: ^/corresponsalia/estadofondo, roles: ROLE_RENDICION_ADMIN }
        - { path: ^/corresponsalia/revisionrendicion, roles: ROLE_RENDICION_ADMIN }

        - { path: ^/corresponsalia/cambio, roles: ROLE_RENDICION_CORRESPONSALIA }
        - { path: ^/corresponsalia/rendirgasto, roles: ROLE_RENDICION_CORRESPONSALIA }

        



        




        