security:
    firewalls:
        frontend:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: /usuario/login
                check_path: /usuario/login_check
                default_target_path: /corresponsalia/inicio
                always_use_default_target_path: true
            logout:
                path: usuario_logout
                target: /usuario/login


            
    providers:
        usuarios:
            entity: { class: Administracion\UsuarioBundle\Entity\User, property: username }
        
    encoders:
       # Administracion\UsuarioBundle\Entity\User: { algorithm: plaintext }

        Administracion\UsuarioBundle\Entity\User: 
            algorithm: md5
            iterations:       0
            encode_as_base64: false

        #Symfony\Component\Security\Core\User\User: plaintext
        
    access_control:
        #usuario general
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/corresponsalia/inicio, roles: ROLE_USER }

        - { path: ^/usuario/cambioclave, roles: ROLE_USER }
        - { path: ^/usuario/actualizacambioclave, roles: ROLE_USER }

        #super admin
        - { path: ^/usuario, roles: ROLE_SUPERADMIN }
        - { path: ^/corresponsalia/reporte/aurendicion, roles: ROLE_SUPERADMIN }

        #combinados
        - { path: ^/corresponsalia/periodorendicion, roles: [ROLE_RENDICION_ADMIN, ROLE_RENDICION_CORRESPONSALIA, ROLE_CONSULTA] }
        - { path: ^/corresponsalia/reporte/rendicion, roles: [ROLE_RENDICION_ADMIN, ROLE_RENDICION_CORRESPONSALIA,ROLE_SUPERADMIN,ROLE_CONSULTA] }
        - { path: ^/corresponsalia/reporte/auef, roles: [ROLE_RENDICION_ADMIN,ROLE_SUPERADMIN] }

        

        #administrador
        - { path: ^/corresponsalia/descripciongasto, roles: [ROLE_RENDICION_ADMIN, ROLE_CONSULTA] }
        - { path: ^/corresponsalia/tipomoneda, roles: ROLE_RENDICION_ADMIN }
        - { path: ^/corresponsalia/tipocorresponsalia, roles: ROLE_RENDICION_ADMIN }
        - { path: ^/corresponsalia/corresponsalia, roles: ROLE_RENDICION_ADMIN }
        - { path: ^/corresponsalia/estadofondo, roles: ROLE_RENDICION_ADMIN }
        - { path: ^/corresponsalia/revisionrendicion, roles: ROLE_RENDICION_ADMIN }

        #corresponsal
        - { path: ^/corresponsalia/cambio, roles: ROLE_RENDICION_CORRESPONSALIA }
        - { path: ^/corresponsalia/rendirgasto, roles: ROLE_RENDICION_CORRESPONSALIA }


        #ROLES DE MODULO DE PERSONAL
        - { path: ^/corresponsalia/personal/consulta, roles: [ROLE_SUPERADMIN, ROLE_PERSONAL, ROLE_PERSONAL_CONSULTA]}
        - { path: ^/corresponsalia/personal/e, roles: [ROLE_SUPERADMIN, ROLE_PERSONAL]}
        - { path: ^/corresponsalia/cargo,        roles: [ROLE_SUPERADMIN, ROLE_PERSONAL]}

        #ROLES DE MODULO DE CONSULTORIA (DATOS, COMENTARIOS Y DOCUMENTOS)
        - { path: ^/corresponsalia/datoslegales, roles: [ROLE_SUPERADMIN,ROLE_CONSULTORIA,ROLE_CONSULTA]}
        - { path: ^/corresponsalia/comentarios,  roles: [ROLE_SUPERADMIN,ROLE_CONSULTORIA]}
        - { path: ^/corresponsalia/documentos,   roles: [ROLE_SUPERADMIN,ROLE_CONSULTORIA]}
        - { path: ^/corresponsalia/documento/edit, roles: ROLE_SUPERADMIN}

        #--MODULO DE TECNOLOGIA
        - { path: ^/corresponsalia/tecnocategoria,  roles: [ROLE_SUPERADMIN, ROLE_TECNO_ADMIN, ROLE_TECNO_CORRESPONSALIA]}
        - { path: ^/corresponsalia/tecnomarca,      roles: [ROLE_SUPERADMIN, ROLE_TECNO_ADMIN, ROLE_TECNO_CORRESPONSALIA]}
        - { path: ^/corresponsalia/tecnoequipo,     roles: [ROLE_SUPERADMIN, ROLE_TECNO_ADMIN, ROLE_TECNO_CORRESPONSALIA]}
        - { path: ^/corresponsalia/tecnoasignar,    roles: [ROLE_SUPERADMIN, ROLE_TECNO_ADMIN, ROLE_TECNO_CORRESPONSALIA]}
        - { path: ^/corresponsalia/tecnomodelo,     roles: [ROLE_SUPERADMIN, ROLE_TECNO_ADMIN, ROLE_TECNO_CORRESPONSALIA]}
        - { path: ^/corresponsalia/tecnobitacora,   roles: [ROLE_SUPERADMIN, ROLE_TECNO_ADMIN, ROLE_TECNO_CORRESPONSALIA]}

