<?php

namespace Proxies\__CG__\Frontend\CorresponsaliaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Estadofondo extends \Frontend\CorresponsaliaBundle\Entity\Estadofondo implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setSaldoinicial($saldoinicial)
    {
        $this->__load();
        return parent::setSaldoinicial($saldoinicial);
    }

    public function getSaldoinicial()
    {
        $this->__load();
        return parent::getSaldoinicial();
    }

    public function setRecursorecibido($recursorecibido)
    {
        $this->__load();
        return parent::setRecursorecibido($recursorecibido);
    }

    public function getRecursorecibido()
    {
        $this->__load();
        return parent::getRecursorecibido();
    }

    public function setFechaasignacion($fechaasignacion)
    {
        $this->__load();
        return parent::setFechaasignacion($fechaasignacion);
    }

    public function getFechaasignacion()
    {
        $this->__load();
        return parent::getFechaasignacion();
    }

    public function setSaldofinal($saldofinal)
    {
        $this->__load();
        return parent::setSaldofinal($saldofinal);
    }

    public function getSaldofinal()
    {
        $this->__load();
        return parent::getSaldofinal();
    }

    public function setPagos($pagos)
    {
        $this->__load();
        return parent::setPagos($pagos);
    }

    public function getPagos()
    {
        $this->__load();
        return parent::getPagos();
    }

    public function setObservacion($observacion)
    {
        $this->__load();
        return parent::setObservacion($observacion);
    }

    public function getObservacion()
    {
        $this->__load();
        return parent::getObservacion();
    }

    public function setResponsable(\Administracion\UsuarioBundle\Entity\Perfil $responsable = NULL)
    {
        $this->__load();
        return parent::setResponsable($responsable);
    }

    public function getResponsable()
    {
        $this->__load();
        return parent::getResponsable();
    }

    public function setPeriodorendicion(\Frontend\CorresponsaliaBundle\Entity\Periodorendicion $periodorendicion = NULL)
    {
        $this->__load();
        return parent::setPeriodorendicion($periodorendicion);
    }

    public function getPeriodorendicion()
    {
        $this->__load();
        return parent::getPeriodorendicion();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'saldoinicial', 'recursorecibido', 'fechaasignacion', 'saldofinal', 'pagos', 'observacion', 'responsable', 'periodorendicion');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}