<?php

namespace Proxies\__CG__\Frontend\CorresponsaliaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Cambio extends \Frontend\CorresponsaliaBundle\Entity\Cambio implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setMontocambiodolar($montocambiodolar)
    {
        $this->__load();
        return parent::setMontocambiodolar($montocambiodolar);
    }

    public function getMontocambiodolar()
    {
        $this->__load();
        return parent::getMontocambiodolar();
    }

    public function setFechahoraregistro($fechahoraregistro)
    {
        $this->__load();
        return parent::setFechahoraregistro($fechahoraregistro);
    }

    public function getFechahoraregistro()
    {
        $this->__load();
        return parent::getFechahoraregistro();
    }

    public function setResponsable(\Administracion\UsuarioBundle\Entity\Perfil $responsable = NULL)
    {
        $this->__load();
        return parent::setResponsable($responsable);
    }

    public function getResponsable()
    {
        $this->__load();
        return parent::getResponsable();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setPeriodorendicion(\Frontend\CorresponsaliaBundle\Entity\Periodorendicion $periodorendicion = NULL)
    {
        $this->__load();
        return parent::setPeriodorendicion($periodorendicion);
    }

    public function getPeriodorendicion()
    {
        $this->__load();
        return parent::getPeriodorendicion();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'montocambiodolar', 'fechahoraregistro', 'responsable', 'periodorendicion');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}