corresponsalia_inicio:
    pattern:  /inicio
    defaults: { _controller: CorresponsaliaBundle:Default:inicio }


################################################################################

tipocorresponsalia:
    pattern:  /tipocorresponsalia/lista
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:index" }

tipocorresponsalia_show:
    pattern:  /{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:show" }

tipocorresponsalia_new:
    pattern:  /new
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:new" }

tipocorresponsalia_create:
    pattern:  /create
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:create" }
    requirements: { _method: post }

tipocorresponsalia_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:edit" }

tipocorresponsalia_update:
    pattern:  /{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:update" }
    requirements: { _method: post|put }

tipocorresponsalia_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:delete" }
    requirements: { _method: post|delete }
