corresponsalia_inicio:
    pattern:  /inicio
    defaults: { _controller: CorresponsaliaBundle:Default:inicio }


corresponsalia_guardatemprendicion:
    pattern:  /guardatemprendicion/
    defaults: { _controller: CorresponsaliaBundle:Default:guardatemprendicion }


corresponsalia_ajax_gasfun:
    pattern:  /ajax/gasfun/{datos}
    defaults: { _controller: CorresponsaliaBundle:Ajax:gasfun }
    
corresponsalia_ajax_formdescripciongasto:
    pattern:  /ajax/formdescripciongasto/{idtipo}/{data}
    defaults: { _controller: CorresponsaliaBundle:Ajax:formdescripciongasto }

################################################################################

tipocorresponsalia:
    pattern:  /tipocorresponsalia/lista
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:index" }

tipocorresponsalia_show:
    pattern:  /{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:show" }

tipocorresponsalia_new:
    pattern:  /new
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:new" }

tipocorresponsalia_create:
    pattern:  /create
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:create" }
    requirements: { _method: post }

tipocorresponsalia_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:edit" }

tipocorresponsalia_update:
    pattern:  /{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:update" }
    requirements: { _method: post|put }

tipocorresponsalia_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:delete" }
    requirements: { _method: post|delete }

################################################################################

tipomoneda:
    pattern:  /tipomoneda
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:index" }

tipomoneda_show:
    pattern:  /tipomoneda/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:show" }

tipomoneda_new:
    pattern:  /tipomoneda/new
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:new" }

tipomoneda_create:
    pattern:  /tipomoneda/create
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:create" }
    requirements: { _method: post }

tipomoneda_edit:
    pattern:  /tipomoneda/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:edit" }

tipomoneda_update:
    pattern:  /tipomoneda/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:update" }
    requirements: { _method: post|put }

tipomoneda_delete:
    pattern:  /tipomoneda/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:delete" }
    requirements: { _method: post|delete }


################################################################################

corresponsalia:
    pattern:  /corresponsalia
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:index" }

corresponsalia_show:
    pattern:  /corresponsalia/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:show" }

corresponsalia_new:
    pattern:  /corresponsalia/new
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:new" }

corresponsalia_create:
    pattern:  /corresponsalia/reate
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:create" }
    requirements: { _method: post }

corresponsalia_edit:
    pattern:  /corresponsalia/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:edit" }

corresponsalia_update:
    pattern:  /corresponsalia/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:update" }
    requirements: { _method: post|put }

corresponsalia_delete:
    pattern:  /corresponsalia/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:delete" }
    requirements: { _method: post|delete }

################################################################################

estadofondo:
    pattern:  /estadofondo
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:index" }

estadofondo_show:
    pattern:  /estadofondo/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:show" }

estadofondo_new:
    pattern:  /estadofondo/new
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:new" }

estadofondo_create:
    pattern:  /estadofondo/create
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:create" }
    requirements: { _method: post }

estadofondo_edit:
    pattern:  /estadofondo/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:edit" }

estadofondo_update:
    pattern:  /estadofondo/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:update" }
    requirements: { _method: post|put }

estadofondo_delete:
    pattern:  /estadofondo/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:delete" }
    requirements: { _method: post|delete }
