corresponsalia_inicio:
    pattern:  /inicio
    defaults: { _controller: CorresponsaliaBundle:Default:inicio }

corresponsalia_rendirgasto:
    pattern:  /rendirgasto/{idperiodo}
    defaults: { _controller: CorresponsaliaBundle:Default:rendirgasto }
    
corresponsalia_guardarendicion:
    pattern:  /guardarendicion/{idperiodo}
    defaults: { _controller: CorresponsaliaBundle:Default:guardarendicion }

corresponsalia_editarendicion:
    pattern:  /editarendicion/{idrendicion}/{idperiodo}
    defaults: { _controller: CorresponsaliaBundle:Default:editarendicion }
    
tipocorresponsalia_actualizarendicion:
    pattern:  /actualizarendicion/{idrendicion}/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Default:actualizarendicion" }
    requirements: { _method: post|put }
    
corresponsalia_borrarrendicion:
    pattern:  /borrarrendicion/{idrendicion}/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Default:borrarrendicion" }
    requirements: { _method: post|delete }
    
corresponsalia_ajax_gasfun:
    pattern:  /ajax/gasfun/{datos}
    defaults: { _controller: CorresponsaliaBundle:Ajax:gasfun }
    
corresponsalia_ajax_formdescripciongasto:
    pattern:  /ajax/formdescripciongasto/{idtipo}/{data}
    defaults: { _controller: CorresponsaliaBundle:Ajax:formdescripciongasto }

corresponsalia_estatusrendicion:
    pattern:  /estatusrendicion/{idperiodo}/{estatus}
    defaults: { _controller: CorresponsaliaBundle:Default:estatusrendicion }
    
corresponsalia_revisionrendicion:
    pattern:  /revisionrendicion/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Default:revisionrendicion" }
    
   
corresponsalia_guardarevisionrendicion:
    pattern:  /guardarevisionrendicion/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Default:guardarevisionrendicion" }
################################################################################

tipocorresponsalia:
    pattern:  /tipocorresponsalia/lista
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:index" }

tipocorresponsalia_show:
    pattern:  /{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:show" }

tipocorresponsalia_new:
    pattern:  /new
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:new" }

tipocorresponsalia_create:
    pattern:  /create
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:create" }
    requirements: { _method: post }

tipocorresponsalia_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:edit" }

tipocorresponsalia_update:
    pattern:  /{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:update" }
    requirements: { _method: post|put }

tipocorresponsalia_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:delete" }
    requirements: { _method: post|delete }

################################################################################

tipomoneda:
    pattern:  /tipomoneda
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:index" }

tipomoneda_show:
    pattern:  /tipomoneda/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:show" }

tipomoneda_new:
    pattern:  /tipomoneda/new
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:new" }

tipomoneda_create:
    pattern:  /tipomoneda/create
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:create" }
    requirements: { _method: post }

tipomoneda_edit:
    pattern:  /tipomoneda/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:edit" }

tipomoneda_update:
    pattern:  /tipomoneda/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:update" }
    requirements: { _method: post|put }

tipomoneda_delete:
    pattern:  /tipomoneda/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:delete" }
    requirements: { _method: post|delete }


################################################################################

corresponsalia:
    pattern:  /corresponsalia
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:index" }

corresponsalia_show:
    pattern:  /corresponsalia/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:show" }

corresponsalia_new:
    pattern:  /corresponsalia/new
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:new" }

corresponsalia_create:
    pattern:  /corresponsalia/reate
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:create" }
    requirements: { _method: post }

corresponsalia_edit:
    pattern:  /corresponsalia/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:edit" }

corresponsalia_update:
    pattern:  /corresponsalia/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:update" }
    requirements: { _method: post|put }

corresponsalia_delete:
    pattern:  /corresponsalia/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:delete" }
    requirements: { _method: post|delete }

################################################################################

   
estadofondo:
    pattern:  /estadofondo/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:index" }

estadofondo_show:
    pattern:  /estadofondo/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:show" }

estadofondo_new:
    pattern:  /estadofondo/new/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:new" }

estadofondo_create:
    pattern:  /estadofondo/create/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:create" }
    requirements: { _method: post }

estadofondo_edit:
    pattern:  /estadofondo/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:edit" }

estadofondo_update:
    pattern:  /estadofondo/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:update" }
    requirements: { _method: post|put }

estadofondo_delete:
    pattern:  /estadofondo/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:delete" }
    requirements: { _method: post|delete }

################################################################################

cambio:
    pattern:  /cambio/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Cambio:index" }

cambio_show:
    pattern:  /cambio/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Cambio:show" }

cambio_new:
    pattern:  /cambio/new/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Cambio:new" }

cambio_create:
    pattern:  /cambio/create/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Cambio:create" }
    requirements: { _method: post }

cambio_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Cambio:edit" }

cambio_update:
    pattern:  /cambio/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Cambio:update" }
    requirements: { _method: post|put }

cambio_delete:
    pattern:  /cambio/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Cambio:delete" }
    requirements: { _method: post|delete }

################################################################################
revision_periodorendicion:
    pattern:  /revisionperiodorendicion
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:revisionperiodorendicion" }
    
periodorendicion:
    pattern:  /periodorendicion
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:index" }

periodorendicion_show:
    pattern:  /periodorendicion/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:show" }

periodorendicion_new:
    pattern:  /periodorendicion/new
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:new" }

periodorendicion_create:
    pattern:  /periodorendicion/create
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:create" }
    requirements: { _method: post }

periodorendicion_edit:
    pattern:  /periodorendicion/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:edit" }

periodorendicion_update:
    pattern:  /periodorendicion/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:update" }
    requirements: { _method: post|put }

periodorendicion_delete:
    pattern:  /periodorendicion/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:delete" }
    requirements: { _method: post|delete }

################################################################################

cobertura:
    pattern:  /cobertura/lista/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Cobertura:index" }

cobertura_show:
    pattern:  /cobertura/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Cobertura:show" }

cobertura_new:
    pattern:  /cobertura/new/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Cobertura:new" }

cobertura_create:
    pattern:  /cobertura/create/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Cobertura:create" }
    requirements: { _method: post }

cobertura_edit:
    pattern:  /cobertura/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Cobertura:edit" }

cobertura_update:
    pattern:  /cobertura/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Cobertura:update" }
    requirements: { _method: post|put }

cobertura_delete:
    pattern:  /cobertura/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Cobertura:delete" }
    requirements: { _method: post|delete }

<<<<<<< HEAD

=======
>>>>>>> master
#######################################################################################################################
#
#                                       RUTAS CONSULTORIA JURIDICA
#
#######################################################################################################################

#PERSONAL
personal:
    pattern:  /personal
    defaults: { _controller: "CorresponsaliaBundle:Personal:index" }

personal_show:
    pattern:  /personal/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Personal:show" }

personal_new:
    pattern:  /personal/new
    defaults: { _controller: "CorresponsaliaBundle:Personal:new" }

personal_create:
    pattern:  /personal/create
    defaults: { _controller: "CorresponsaliaBundle:Personal:create" }
    requirements: { _method: post }

personal_edit:
    pattern:  /personal/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Personal:edit" }

personal_update:
    pattern:  /personal/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Personal:update" }
    requirements: { _method: post|put }

personal_delete:
    pattern:  /personal/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Personal:delete" }
    requirements: { _method: post|delete }

reporteconsultoria:
    pattern: /consultoria/reportes
    defaults: { _controller: "CorresponsaliaBundle:Personal:reporte"}

reportepersonal:
    pattern: /personal/reporte
    defaults: { _controller: "CorresponsaliaBundle:Personal:generareporte"}

#CARGO
cargo:
    pattern:  /cargo
    defaults: { _controller: "CorresponsaliaBundle:Cargo:index" }

cargo_show:
    pattern:  /cargo/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Cargo:show" }

cargo_new:
    pattern:  /cargo/new
    defaults: { _controller: "CorresponsaliaBundle:Cargo:new" }

cargo_create:
    pattern:  /cargo/create
    defaults: { _controller: "CorresponsaliaBundle:Cargo:create" }
    requirements: { _method: post }

cargo_edit:
    pattern:  /cargo/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Cargo:edit" }

cargo_update:
    pattern:  /cargo/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Cargo:update" }
    requirements: { _method: post|put }

cargo_delete:
    pattern:  /cargo/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Cargo:delete" }
    requirements: { _method: post|delete }

#REPRESENTANTE
representante:
    pattern:  /representante
    defaults: { _controller: "CorresponsaliaBundle:Representante:index" }

representante_show:
    pattern:  /representante/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Representante:show" }

representante_new:
    pattern:  /representante/new
    defaults: { _controller: "CorresponsaliaBundle:Representante:new" }

representante_create:
    pattern:  /representante/create
    defaults: { _controller: "CorresponsaliaBundle:Representante:create" }
    requirements: { _method: post }

representante_edit:
    pattern:  /representante/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Representante:edit" }

representante_update:
    pattern:  /representante/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Representante:update" }
    requirements: { _method: post|put }

representante_delete:
    pattern:  /representante/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Representante:delete" }
    requirements: { _method: post|delete }

#DATOS JURIDICOS

datoslegales:
    pattern:  /datoslegales
    defaults: { _controller: "CorresponsaliaBundle:Datoslegales:index" }

datoslegales_show:
    pattern:  /datoslegales/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Datoslegales:show" }

#datoslegales_new:
#    pattern:  /datoslegales/new
#    defaults: { _controller: "CorresponsaliaBundle:Datoslegales:new" }

#datoslegales_create:
#    pattern:  /datoslegales/create
#    defaults: { _controller: "CorresponsaliaBundle:Datoslegales:create" }
#    requirements: { _method: post }

datoslegales_edit:
    pattern:  /datoslegales/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Datoslegales:edit" }

datoslegales_update:
    pattern:  /datoslegales/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Datoslegales:update" }
    requirements: { _method: post|put }

datoslegales_delete:
    pattern:  /datoslegales/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Datoslegales:delete" }
    requirements: { _method: post|delete }

#CONTRATO
contrato:
    pattern:  /contrato
    defaults: { _controller: "CorresponsaliaBundle:Contrato:index" }

contrato_show:
    pattern: /contrato/detalle/{id}
    defaults: { _controller: "CorresponsaliaBundle:Contrato:show"}

contrato_new:
    pattern:  /contrato/new
    defaults: { _controller: "CorresponsaliaBundle:Contrato:new" }

contrato_create:
    pattern:  /contrato/create
    defaults: { _controller: "CorresponsaliaBundle:Contrato:create" }
    requirements: { _method: post }

contrato_edit:
    pattern:  /contrato/edit
    defaults: { _controller: "CorresponsaliaBundle:Contrato:edit" }

contrato_update:
    pattern:  /contrato/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Contrato:update" }
    requirements: { _method: post|put }

contrato_delete:
    pattern:  /contrato/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Contrato:delete" }
    requirements: { _method: post|delete }

