corresponsalia_tasacambio:
    pattern:  /tasacambio
    defaults: { _controller: CorresponsaliaBundle:Default:tasacambio }
    
corresponsalia_inicio:
    pattern:  /inicio
    defaults: { _controller: CorresponsaliaBundle:Default:inicio }

corresponsalia_rendirgasto:
    pattern:  /rendirgasto/{idperiodo}
    defaults: { _controller: CorresponsaliaBundle:Default:rendirgasto }

corresponsalia_rendirgastofunhon:
    pattern:  /rendirgastofunhon/{idperiodo}
    defaults: { _controller: CorresponsaliaBundle:Default:rendirgastofunhon }
    
corresponsalia_rendirgastocob:
    pattern:  /rendirgastocob/{idcobertura}
    defaults: { _controller: CorresponsaliaBundle:Default:rendirgastocob }
    
corresponsalia_guardarendicion:
    pattern:  /guardarendicion/{idperiodo}
    defaults: { _controller: CorresponsaliaBundle:Default:guardarendicion }

corresponsalia_editarendicion:
    pattern:  /editarendicion/{idrendicion}/{idperiodo}
    defaults: { _controller: CorresponsaliaBundle:Default:editarendicion }
    
tipocorresponsalia_actualizarendicion:
    pattern:  /actualizarendicion/{idrendicion}/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Default:actualizarendicion" }
    requirements: { _method: post|put }
    
corresponsalia_borrarrendicion:
    pattern:  /borrarrendicion/{idrendicion}/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Default:borrarrendicion" }
    requirements: { _method: post|delete }
    
corresponsalia_ajax_gasfun:
    pattern:  /ajax/gasfun/{datos}
    defaults: { _controller: CorresponsaliaBundle:Ajax:gasfun }
    
corresponsalia_ajax_formdescripciongasto:
    pattern:  /ajax/formdescripciongasto/{idtipo}/{data}
    defaults: { _controller: CorresponsaliaBundle:Ajax:formdescripciongasto }

corresponsalia_estatusrendicion:
    pattern:  /estatusrendicion/{idperiodo}/{estatus}
    defaults: { _controller: CorresponsaliaBundle:Default:estatusrendicion }
    
corresponsalia_revisionrendicion:
    pattern:  /revisionrendicion/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Default:revisionrendicion" }
    
   
corresponsalia_guardarevisionrendicion:
    pattern:  /guardarevisionrendicion/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Default:guardarevisionrendicion" }
################################################################################

tipocorresponsalia:
    pattern:  /tipocorresponsalia/lista
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:index" }

tipocorresponsalia_show:
    pattern:  /{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:show" }

tipocorresponsalia_new:
    pattern:  /new
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:new" }

tipocorresponsalia_create:
    pattern:  /create
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:create" }
    requirements: { _method: post }

tipocorresponsalia_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:edit" }

tipocorresponsalia_update:
    pattern:  /{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:update" }
    requirements: { _method: post|put }

tipocorresponsalia_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Tipocorresponsalia:delete" }
    requirements: { _method: post|delete }

################################################################################

tipomoneda:
    pattern:  /tipomoneda
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:index" }

tipomoneda_show:
    pattern:  /tipomoneda/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:show" }

tipomoneda_new:
    pattern:  /tipomoneda/new
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:new" }

tipomoneda_create:
    pattern:  /tipomoneda/create
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:create" }
    requirements: { _method: post }

tipomoneda_edit:
    pattern:  /tipomoneda/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:edit" }

tipomoneda_update:
    pattern:  /tipomoneda/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:update" }
    requirements: { _method: post|put }

tipomoneda_delete:
    pattern:  /tipomoneda/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Tipomoneda:delete" }
    requirements: { _method: post|delete }


################################################################################

corresponsalia:
    pattern:  /corresponsalia
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:index" }

corresponsalia_show:
    pattern:  /corresponsalia/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:show" }

corresponsalia_new:
    pattern:  /corresponsalia/new
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:new" }

corresponsalia_create:
    pattern:  /corresponsalia/reate
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:create" }
    requirements: { _method: post }

corresponsalia_edit:
    pattern:  /corresponsalia/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:edit" }

corresponsalia_update:
    pattern:  /corresponsalia/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:update" }
    requirements: { _method: post|put }

corresponsalia_delete:
    pattern:  /corresponsalia/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Corresponsalia:delete" }
    requirements: { _method: post|delete }

################################################################################

   
estadofondo:
    pattern:  /estadofondo/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:index" }

estadofondo_show:
    pattern:  /estadofondo/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:show" }

estadofondo_new:
    pattern:  /estadofondo/new/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:new" }

estadofondo_create:
    pattern:  /estadofondo/create/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:create" }
    requirements: { _method: post }

estadofondo_edit:
    pattern:  /estadofondo/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:edit" }

estadofondo_update:
    pattern:  /estadofondo/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:update" }
    requirements: { _method: post|put }

estadofondo_delete:
    pattern:  /estadofondo/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Estadofondo:delete" }
    requirements: { _method: post|delete }

################################################################################

cambio:
    pattern:  /cambio/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Cambio:index" }

cambio_show:
    pattern:  /cambio/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Cambio:show" }

cambio_new:
    pattern:  /cambio/new/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Cambio:new" }

cambio_create:
    pattern:  /cambio/create/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Cambio:create" }
    requirements: { _method: post }

cambio_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Cambio:edit" }

cambio_update:
    pattern:  /cambio/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Cambio:update" }
    requirements: { _method: post|put }

cambio_delete:
    pattern:  /cambio/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Cambio:delete" }
    requirements: { _method: post|delete }

################################################################################
revision_periodorendicion:
    pattern:  /revisionperiodorendicion
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:revisionperiodorendicion" }
    
periodorendicion:
    pattern:  /periodorendicion
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:index" }

periodorendicion_show:
    pattern:  /periodorendicion/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:show" }

periodorendicion_new:
    pattern:  /periodorendicion/new
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:new" }

periodorendicion_create:
    pattern:  /periodorendicion/create
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:create" }
    requirements: { _method: post }

periodorendicion_edit:
    pattern:  /periodorendicion/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:edit" }

periodorendicion_update:
    pattern:  /periodorendicion/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:update" }
    requirements: { _method: post|put }

periodorendicion_delete:
    pattern:  /periodorendicion/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Periodorendicion:delete" }
    requirements: { _method: post|delete }

################################################################################

cobertura:
    pattern:  /cobertura/lista/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Cobertura:index" }

cobertura_show:
    pattern:  /cobertura/{id}/show
    defaults: { _controller: "CorresponsaliaBundle:Cobertura:show" }

cobertura_new:
    pattern:  /cobertura/new/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Cobertura:new" }

cobertura_create:
    pattern:  /cobertura/create/{idperiodo}
    defaults: { _controller: "CorresponsaliaBundle:Cobertura:create" }
    requirements: { _method: post }

cobertura_edit:
    pattern:  /cobertura/{id}/edit
    defaults: { _controller: "CorresponsaliaBundle:Cobertura:edit" }

cobertura_update:
    pattern:  /cobertura/{id}/update
    defaults: { _controller: "CorresponsaliaBundle:Cobertura:update" }
    requirements: { _method: post|put }

cobertura_delete:
    pattern:  /cobertura/{id}/delete
    defaults: { _controller: "CorresponsaliaBundle:Cobertura:delete" }
    requirements: { _method: post|delete }
